name: API CI
on:
  push:
    branches: [main, develop]
  pull_request:
      branches: [main, develop]
jobs:
  testing:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repo
            uses: action/checkout@v4  #git clone into runner
          - name: Setup Nodejs
            uses: action/setup-node@v4 # instalar node
            with:
                  node-version: 20.x
          - name: Install Dependencies # instlr las dependencies
            run: npm install
          - name: Run unit and integrate tests
            run: npm run test
          #- name: Run code linter
          #- run: npm run lint